/**
 * Bake the hand-inked rules into static SVG data URIs.
 *
 * Only one survives the dark redesign: the tear line across the manifest, which
 * keeps a trace of the paperwork idea without dragging the whole hand-drawn
 * surface along with it.
 *
 *   node scripts/build-ink.mjs
 *
 * Why bake: the look wants a wobbly, hand-drawn line sitting on flat fills. The
 * obvious implementation is feTurbulence + feDisplacementMap on the borders,
 * but an SVG filter on every card in a scrolling grid repaints the whole filter
 * region on every scroll frame. So the jitter is computed here, once, and
 * shipped as plain static paths. Same picture, zero runtime filter cost.
 *
 * Output: src/app/styles/ink.css (generated — do not hand-edit).
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

/** Deterministic PRNG so the linework is identical on every build. */
function rng(seed) {
  let s = seed >>> 0;
  return () => {
    s = (s * 1664525 + 1013904223) >>> 0;
    return s / 4294967296;
  };
}

const r2 = (n) => Math.round(n * 100) / 100;

/**
 * A wobbly horizontal rule that tiles seamlessly: both ends are pinned to the
 * same y, and the control points in between drift by at most `amp`.
 */
function rule(seed, { width = 240, mid = 4, amp = 1.5, steps = 8 } = {}) {
  const rand = rng(seed);
  let d = `M0 ${mid}`;
  for (let i = 1; i <= steps; i++) {
    const x = (width / steps) * i;
    const y = i === steps ? mid : mid + (rand() - 0.5) * 2 * amp;
    const cx = x - width / steps / 2;
    d += ` Q${r2(cx)} ${r2(mid + (rand() - 0.5) * 2 * amp)} ${r2(x)} ${r2(y)}`;
  }
  return d;
}

/**
 * A wobbly rounded rectangle for `border-image`. Corners live inside the
 * 9-slice corner regions so they survive being sliced; the straight runs
 * stretch, which keeps the amplitude and only shifts the frequency.
 */
function frame(seed, { size = 120, radius = 16, amp = 1.1, perSide = 5 } = {}) {
  const rand = rng(seed);
  const j = () => (rand() - 0.5) * 2 * amp;
  const S = size;
  const R = radius;
  const seg = (x1, y1, x2, y2) => {
    let d = "";
    for (let i = 1; i <= perSide; i++) {
      const t = i / perSide;
      const x = x1 + (x2 - x1) * t + (i === perSide ? 0 : j());
      const y = y1 + (y2 - y1) * t + (i === perSide ? 0 : j());
      d += ` L${r2(x)} ${r2(y)}`;
    }
    return d;
  };
  let d = `M${R} 0`;
  d += seg(R, 0, S - R, 0);
  d += ` Q${S} 0 ${S} ${R}`;
  d += seg(S, R, S, S - R);
  d += ` Q${S} ${S} ${S - R} ${S}`;
  d += seg(S - R, S, R, S);
  d += ` Q0 ${S} 0 ${S - R}`;
  d += seg(0, S - R, 0, R);
  d += ` Q0 0 ${R} 0 Z`;
  return d;
}

/** Data URI. Quotes and # are the only characters that need escaping here. */
function uri(svg) {
  return `url("data:image/svg+xml,${svg
    .replace(/\n\s*/g, "")
    .replace(/"/g, "'")
    .replace(/#/g, "%23")
    .replace(/</g, "%3C")
    .replace(/>/g, "%3E")}")`;
}

/* Light, for a dark surface. Opacity is applied in CSS, not baked here. */
const INK = "%23A7B3B1";

const ruleSvg = (d, w) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} 8" width="${w}" height="8">
     <path d="${d}" fill="none" stroke="${INK}" stroke-width="1.6" stroke-linecap="round"/>
   </svg>`;

const lines = [
  "/* GENERATED by scripts/build-ink.mjs — do not hand-edit. */",
  "/* Hand-inked linework, baked to static paths so nothing filters at paint time. */",
  "",
  ":root {",
  `  --ink-rule-a: ${uri(ruleSvg(rule(11), 240))};`,
  "}",
  "",
];

writeFileSync(
  fileURLToPath(new URL("../src/app/styles/ink.css", import.meta.url)),
  lines.join("\n"),
  "utf8",
);
console.log("wrote src/app/styles/ink.css");
